##################################################################################################
#  Nginx Configmap
##################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            root /usr/share/nginx/html;
            location / {
                try_files $uri $uri/ /index.html;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }
---
##################################################################################################
#  Nginx Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: nginx-dev
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 30001
  type: NodePort
---
##################################################################################################
#  Nginx Deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dev
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: ghcr.io/sos-hub-vn/sos-website:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      imagePullSecrets:
        - name: gitcred
---
##################################################################################################
#  Nginx ingress
##################################################################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-dev
                port:
                  number: 80
