name: deploy-dev

on:
  push:
    branches:
      - 'master'
      - 'kube-config'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sos-hub-vn
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sos-hub-vn/sos-website:dev-latest
            ghcr.io/sos-hub-vn/sos-website:dev-1.0.0
      -
        name: Push to k8s
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.VINACIS_KUBE_CONFIG }}
          command: apply -f ./k8s/deploy-dev.yml --namespace=frontend
      -
        name: Rollout K8s deployment restart
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.VINACIS_KUBE_CONFIG }}
          command: rollout restart deployment nginx-deployment-dev --namespace=frontend

